[FIX] _sanitize_phone_number isinstance(targets, dict) when method is called from write method AttributeError: 'res.users' object has no attribute 'company' AttributeError: 'res.company' object has no attribute 'ref'