fix: academy_support_staff._sanitize_phone_number
[FIX] _sanitize_phone_number by Nacho Codeseda
isinstance(targets, dict) when method is called from write method
AttributeError: 'res.users' object has no attribute 'company'
AttributeError: 'res.company' object has no attribute 'ref'